context:
  name: dataframely
  version: "1.0.0"
  python_min: "3.11.*"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 56681a29e424dbc1e6b2c2decb879eea46abca06e416742dfccd565dda627c65

build:
  number: 0
  skip: not (match(python, python_min) and is_abi3 == 'true')
  python:
    version_independent: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.7,<2
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - python-abi3
    - pip
    - maturin >=1.7,<2
  run:
    - python
    - numpy
    - polars >=1.12
  run_constraints:
    - mypy >=1.12
    - sqlalchemy >=2

tests:
  - python:
      python_version: ${{ python_min }}
      imports:
        - dataframely
      pip_check: true

about:
  homepage: https://github.com/Quantco/dataframely
  summary: A declarative, polars-native data frame validation library.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://dataframely.readthedocs.io/
  repository: https://github.com/Quantco/dataframely

extra:
  recipe-maintainers:
    - borchero
    - delsner
